In [34]:
import numpy as np
import pandas as pd

In [35]:
df = pd.read_csv('customer.csv')

In [36]:
df.sample(5)

age  gender   review education purchased
38   45  Female     Good    School        No
0    30  Female  Average    School        No
20   57  Female  Average    School       Yes
12   51    Male     Poor    School        No
14   15    Male     Poor        PG       Yes

In [37]:
df = df.iloc[:,2:]

In [38]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:, -1], test_size=0.2)

In [40]:
X_train

review education
45     Poor        PG
49     Good        UG
33     Good        PG
21  Average        PG
30  Average        UG
29  Average        UG
22     Poor        PG
39     Poor        PG
13  Average    School
11     Good        UG
27     Poor        PG
35     Poor    School
17     Poor        UG
7      Poor    School
32  Average        UG
31     Poor    School
6      Good    School
19     Poor        PG
20  Average    School
36     Good        UG
28     Poor    School
46     Poor        PG
9      Good        UG
48     Good        UG
26     Poor        PG
24  Average        PG
47     Good        PG
43     Poor        PG
38     Good    School
14     Poor        PG
5   Average    School
1      Poor        UG
12     Poor    School
8   Average        UG
40     Good    School
3      Good        PG
4   Average        UG
2      Good        PG
15     Poor        UG
23     Good    School

In [41]:
from sklearn.preprocessing import OrdinalEncoder

In [42]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [43]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [44]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [45]:
X_train

array([[0., 2.],
       [2., 1.],
       [2., 2.],
       [1., 2.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [2., 0.]])

In [46]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [47]:
X_train

array([[0., 2.],
       [2., 1.],
       [2., 2.],
       [1., 2.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [2., 0.]])

In [48]:
from sklearn.preprocessing import LabelEncoder

In [49]:
le = LabelEncoder()

In [50]:
le.fit(y_train)

LabelEncoder()

In [51]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [52]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [53]:
y_train

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])